---
- name: Install parted
  package:
    name: parted
    state: present

- name: Create directory
  file:
    path: "{{ mountpoint }}"
    state: directory
  loop:
    - /data
    - /speci
    - /dir

- name: Read device information about the disk
  parted:
    device: "{{ disk }}"
    unit: MiB
  register: disk_info

- name: Create the new primary partition
  parted:
    device: "{{ disk }}"
    number: "{{ part_number }}"
    state: present
    part_type: primary
    label: gpt
    unit: MiB
    part_start: "{{ disk_info.partitions[-1].end + 1 }}MiB"
    part_end: "{{disk_info.partitions[-1].end + part_size }}MiB"

- name: Create filesystem on partition
  filesystem:
    fstype: ext4
    dev: "{{ disk }}{{ part_number }}"

